### ISSUE TITLE
Trajectory Generator

### ISSUE THREAD

**Issue by liorLimudim** [nrutkowski1/INS-GPS-Kalman-Filter#1]
Hi 
I want to check the Kalman Filter with other Trajectories and Noises ,  how can i Generate those?
is there any tool for it ?
i want to make some statistical calculation using different trajectories and different noise pattern.
in your beautiful example i saw you used "Sensorlog" ...
please advise
Lior

**Comment by nrutkowski1** [comment]
Hi Lior, 

Matlab has a free app that you can download on your phone which will use sensors on your phone to measure the GPS position, acceleration, orientation, and angular velocity of your phone. I believe in this example I walked around outside and recorded these measurements with the app. This is where the 'sensorlog..' file in my code came from. You could do the same if you want.

 The other option which was provided to me and included in the repository is creating synthetic data for each of the measurements. You could do this by writing just simple functions and adding random noise to each value produced. I believe Matlab may have other methods for generating synthetic sensor data, you may want to look into this: https://www.mathworks.com/help/fusion/. Unfortunately this is not something I have done specifically so I can't give you a ton more advice. 

-Nathaniel

**Comment by liorLimudim** [comment]
Hi Nathaniel,
thank you very much for your answer.
i am looking of a tool to create a trajectory of a UAv , i was thinking of a flight simulator that output a trajectory, you think there is  ?
and then check this trajectory with your tool and kalman with random noise
Lior

**Comment by nrutkowski1** [comment]
If there is a flight simulator that outputs that data it may just require some work to put into matlab but should work anyways. I personally am not aware of any flight simulators. 

Nathaniel

**Comment by liorLimudim** [comment]
hi Nathaniel,
can you help me in creating  taking nmea tracks for example to the MATRIX of your program ?
Lior
